// Bu dosyanın adı: theme.js
import { StyleSheet } from 'react-native';

export const lightColors = {
  background: '#F2F2F7',
  card: '#FFFFFF',
  text: '#000000',
  subtext: '#6E6E73',
  inputBG: '#E9E9EB',
  separator: '#DCDCDC',
  green: '#34C759',
  red: '#FF3B30',
  header: '#F7F7F8',
  tabBar: '#F7F7F8',
  icon: '#000000',
};

export const darkColors = {
  background: '#000000',
  card: '#1C1C1E',
  text: '#FFFFFF',
  subtext: '#8E8E93',
  inputBG: '#2C2C2E',
  separator: '#38383A',
  green: '#30D158',
  red: '#FF453A',
  header: '#1C1C1E',
  tabBar: '#1C1C1E',
  icon: '#FFFFFF',
};

export const getStyles = (colors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  centeredContainer: { flex: 1, backgroundColor: colors.background, justifyContent: 'center' },
  ozetKarti: { backgroundColor: colors.card, borderRadius: 12, padding: 16, margin: 16 },
  ozetLabel: { color: colors.subtext, fontSize: 16, fontFamily: 'Poppins-Regular' },
  netKarText: { color: colors.green, fontSize: 36, fontFamily: 'Poppins-Bold', marginBottom: 10 },
  ozetSatiri: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 4 },
  ozetDeger: { fontSize: 16, fontFamily: 'Poppins-Bold', color: colors.text },
  separator: { height: StyleSheet.hairlineWidth, backgroundColor: colors.separator, marginVertical: 15 },
  masrafDetay: { fontSize: 12, fontFamily: 'Poppins-Regular', color: colors.subtext, textAlign: 'right', marginTop: -4, marginBottom: 8 },
  formKarti: { backgroundColor: colors.card, borderRadius: 12, padding: 16, marginHorizontal: 16, marginBottom: 16 },
  collapsibleHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  formBaslik: { color: colors.text, fontSize: 18, fontFamily: 'Poppins-Bold' },
  collapsibleContent: { marginTop: 20 },
  inputLabel: { color: colors.subtext, fontSize: 14, fontFamily: 'Poppins-Regular', marginBottom: 5 },
  input: { backgroundColor: colors.inputBG, color: colors.text, borderRadius: 8, padding: 12, fontSize: 16 },
  button: { paddingVertical: 15, borderRadius: 8, alignItems: 'center' },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontFamily: 'Poppins-Bold' },
  listelerContainer: { flexDirection: 'row', paddingHorizontal: 16, marginTop: 10, gap: 10 },
  listeBaslik: { color: colors.text, fontSize: 18, fontFamily: 'Poppins-Bold', marginBottom: 10, textAlign: 'center' },
  kayitItem: { backgroundColor: colors.card, padding: 12, borderRadius: 8, marginBottom: 8 },
  kayitTutar: { fontFamily: 'Poppins-Bold', fontSize: 16 },
  notText: { fontFamily: 'Poppins-Regular', fontSize: 13, color: colors.subtext, marginTop: 3 },
  endDayButton: { backgroundColor: colors.red, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 15, borderRadius: 10, marginHorizontal: 16, marginTop: 20, marginBottom: 40 },
  endDayButtonText: { color: 'white', fontFamily: 'Poppins-Bold', fontSize: 16, marginLeft: 10 },
  summaryContainer: { flexDirection: 'row', justifyContent: 'space-around', padding: 10, paddingHorizontal: 10 },
  summaryBox: { flex: 1, backgroundColor: colors.card, padding: 15, borderRadius: 10, margin: 5, alignItems: 'center' },
  summaryLabel: { color: colors.subtext, fontFamily: 'Poppins-Regular', fontSize: 12, textAlign: 'center' },
  summaryValue: { color: colors.text, fontFamily: 'Poppins-Bold', fontSize: 16, marginTop: 5 },
  historyItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.card, padding: 20, marginHorizontal: 16, marginVertical: 6, borderRadius: 12 },
  dateText: { color: colors.text, fontFamily: 'Poppins-Bold', fontSize: 16 },
  earningsText: { color: colors.subtext, fontFamily: 'Poppins-Regular', fontSize: 14, textAlign: 'right' },
  netProfitText: { fontFamily: 'Poppins-Bold', fontSize: 14, textAlign: 'right' },
  emptyText: { color: colors.subtext, textAlign: 'center', marginTop: 50, fontFamily: 'Poppins-Regular' },
  dateText_detail: { color: colors.text, fontFamily: 'Poppins-Bold', fontSize: 18, textAlign: 'center' },
  kayitItem_detail: { backgroundColor: colors.card, padding: 15, borderRadius: 10, marginBottom: 8, minHeight: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  editButton_detail: { padding: 5 },
  modalContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.6)' },
  modalContent: { width: '85%', backgroundColor: colors.card, borderRadius: 14, padding: 20 },
  modalTitle: { color: colors.text, fontSize: 20, fontFamily: 'Poppins-Bold', marginBottom: 20, textAlign: 'center' },
  modalButton: { flex: 1, padding: 15, borderRadius: 8, alignItems: 'center' },
  cancelButton: { backgroundColor: colors.subtext, marginRight: 5 },
  saveButton: { backgroundColor: colors.green, marginLeft: 5 },
});